### ISSUE TITLE
undo table pivoting

### ISSUE THREAD

**Issue by AcckiyGerman** [datasets/global-house-prices#2]
After a sprint-end review it was mentioned by @rufuspollock that current data.csv output have a bad structure (I had same doubts).

## Acceptance criteria
* [x] the table has readable structure with all the related headers presented in the same file.
* [x] `data verify` is ok

## Tasks
* [x] undo table pivot in the process.py
* [x] respectively fix the datapackage.json structure
* [x] update the readme
* [ ] find a feedback from Irakly

## Analyse
I think that is better to have the same table rotation, as the source file has, but comment a first few rows, which are not the headers.

**Comment by zelima** [comment]
@AcckiyGerman before start working on this, could you please provide an example how the output data will look like - eg. column names and several examples of their values

**Comment by AcckiyGerman** [comment]
## analyse desired data format
Original data:  
![original data](https://user-images.githubusercontent.com/11707682/34253118-951f54e0-e646-11e7-82b9-cb725db8618f.png)  

Unpivoted data (current format)  
![unpivoted data current output](https://user-images.githubusercontent.com/11707682/34253154-b83d11b0-e646-11e7-8de2-3108f8bcf9dc.png)
Contras:
* [ ] nobody knows what are those codes mean at the first glance (Although it is decoded in datapackage.json)
* [ ] Quarters should be translated to usual dates.

Proposed format (similar with original but removed first rows)
![pps original structure with removed first rows](https://user-images.githubusercontent.com/11707682/34253181-d4eaef94-e646-11e7-9276-6829b6cb70c9.png)

Also dates `1991-Q1` will be replaced by `1991-03-31` (Although I don't see why do we need to transform date - to be auto-recognized with some programs?)

**Comment by zelima** [comment]
@AcckiyGerman so you are pivoting it back again? 
I think the best way to go is to remove first rows and unpivot it as well. So you will have following columns 
```
frequency,reference_area,value,unit_of_measure,date,price
```

I would even remove frequency as it seems it's always `Q:Quartelry`

**Comment by zelima** [comment]
@AcckiyGerman to be honest, I would even go crazy and split them out in 4 different resources here:
- nominal/628index - `value=nominal and unit_of_measure=628...`
- real/628index - `value=real and unit_of_measure=628...`
- nominal/771... - `value=nominal and unit_of_measure=771...`
- real/771 - `value=reak and unit_of_measure=721..`

and our you will be left with only 3 columns
```
reference_area,date,price
```

**Comment by zelima** [comment]
>Also dates 1991-Q1 will be replaced by 1991-03-31 (Although I don't see why do we need to transform date - to be auto-recognized with some programs?)

We are trying to tidy data as much as possible and make it as much representable as possible, right? There's nothing wrong with `1991-Q1` of caurse, but imagine using this dataset by yoursef in some of your projects. Do you think `1991-Q1` would be more useful than nice `1991-03-31`? You would not have to write **any** aditional scripts to transfor them into valid dates and use data directly to create Graphs for example.

We are doing our best to represent data in a frictionless way - with best quality we can, so if it would not take too much time and effort I would go and change Q1 to 03-31

**Comment by AcckiyGerman** [comment]
It is now clear with Date, thanks.
>I think the best way to go is to remove first rows and unpivot it as well. So you will have following columns `frequency,reference_area,value,unit_of_measure,date,price`

The date and price is orthogonal in this table, we can't pivot it this way. I will think about it now.

**Comment by zelima** [comment]
@AcckiyGerman but that's what un-pivot would mean:
To turn this:
```
country,jan,feb,mar
france,100,200,300
...
```
into this:
```
country,date,population
france,jan,100
france,feb,200
france,mar,300
...
```

**Comment by AcckiyGerman** [comment]
@zelima so the final structure will be:
* data is split into 4 files (nominal-index, nominal-year-on-year-changes, real-index, real-year-on-year-changes)
* 'Quarterly' is thrown away
* BIS codes are thrown away
* Each row is a date, each column is a country, each cell is a price.
```
# Nominal Year-on-year changes, in per cent
date, Albania, Armenia, Ukraine
1998-03-31, 222, 333, 444
1998-06-30, 225, 337, 434
1998-09-31, 250, 380, 499
```
Now user could easy find any country, or any date.

**Comment by zelima** [comment]
@AcckiyGerman No that's just pivoting on the other side. The structure should be:
```
date,country,price
1998-03-31,Albania,222
1998-06-30,Albania,225
1998-09-31,Albania,250
1998-03-31,Armenia,333
1998-06-39,Armenia,337
1998-06-39,Armenia,337
1998-03-31,Ukraine,444
...
```

**Note: this is just an example - column names may be different - you know better**

Also maybe I do not have much info about BiS code. Maybe that's something useful? you can keep it if so

**Comment by AcckiyGerman** [comment]
I'm really sorry, but I don't understand at all, why to unpivot this table like you want to.
If we take a school multiply table as an example, we have this:
```
_, 1, 2, 3, 4, 5, 6
1, 1, 2, 3, 4, 5, 6
2, 2, 4, 6, 8, 10, 12
3, 3, 6, 9, 12, 15, 18
4, 4, 8, 12, 16, 20, 24
```
and unpivot means transform it like this:
```
1, 1, 1
1, 2, 2
1, 3, 3
1, 4, 4
1, 5, 5
1, 6, 6
2, 1, 2
2, 2, 4
2, 3, 6
2, 4, 8
2, 5, 10
2, 6, 12
3, 1, 3
3, 2, 6
...
...
4, 5, 20
4, 6, 24
```
Right? 
And my strong feeling is that second one is harder to read and to seek in for some data. And this list is only 100 rows long.

Now, back to our property prices. There are 59 countries and 204 dates in it. and if We are really trying to tidy data as much as possible, then transforming:
* square 204 x 59 table
into 
* 12036 rows list
where countries and dates are mixed together - seems to me as **a very unproductive** idea. And remember, then there will be 4 of those tables.
That data will be almost impossible to handle manually.

I just could not image why do so, and how it could help the customers to lurk some price ?

**Comment by zelima** [comment]
@AcckiyGerman pivoted tables work great with small tables like multiplication tables or maybe monthly calendars etc... But as they get bigger it's getting hard to find the points. Imagine 1000X1000 grid or even bigger. 

With un-pivoted tables, you:
* always know the column names (as they are fixed), while in case of pivoted one you have to always  add new column every time data comes in - therefor useless for machines
* normally to place point on graph you need X and Y point and graph libraries take list of X and Y values to plot the graph that is already ready for you when it is un-pivoted - you can directly pass whole data to any graph library, without **any** modifications to the data and it will plot graph for you. While if it is pivoted you will have to first write a script to un-pivot data and then pass to it.
* Even for a human it's easier to find data if it is sorted - you would scroll to your country then scroll till the date (or vice-versa) and the price would sit right next to it. While in the gird table you have to scroll till the country, remember or mark the row somehow then do same for date mark or remember re column and finally find their crossing point. Again this would work for 20X20 gird but it's hard with 204X59 grid

Finally, if you really want to keep the data you can create another 5th resource and keep it there, but personally, I think that would be extra

**Comment by AcckiyGerman** [comment]
@zelima Done, data is splitted into 4 files and each table is unpivoted.

**Comment by AcckiyGerman** [comment]
Closing, as the appropriate PR is accepted after the review
